# Generated by Django 5.2 on 2025-06-20 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploadpicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DL', models.FileField(null=True, upload_to='DL_file/')),
                ('SSN', models.FileField(null=True, upload_to='SSN_file/')),
                ('W2', models.FileField(null=True, upload_to='W2_file/')),
                ('ref', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_number', models.CharField(max_length=500, null=True)),
                ('middle_name', models.CharField(max_length=500, null=True)),
                ('Recent_address', models.CharField(max_length=500, null=True)),
                ('Previous_address', models.CharField(max_length=500, null=True)),
                ('annual_income', models.CharField(max_length=500, null=True)),
                ('Average_income', models.CharField(max_length=500, null=True)),
                ('date_of_birth', models.CharField(max_length=500, null=True)),
                ('social_security', models.CharField(max_length=500, null=True)),
                ('Last_employer', models.CharField(max_length=500, null=True)),
                ('Job_role', models.CharField(max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
