# Generated by Django 5.2 on 2025-06-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undefapp', '0002_profile_account_number_profile_is_frozen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recipient_account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient_bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient_routing_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
