# Generated by Django 5.2 on 2025-06-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undefapp', '0004_transaction_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
